export const LANGUAGES = {
    VI: 'vi',
    EN: 'en'
};

export const path = {
    HOME: '/',
    HOME2: '/home',
    FORGOT_PASSWORD: '/forgot-password',
    MANAGE_EMPLOYEES: '/manage-accounts',
    MANAGE_EMPLOYEES_BY_DEPARTMENT: '/manage-accounts/department',
    SIGN_IN: '/login',
    CUSTOMER_SIGN_IN: '/customer/login',
    CUSTOMER_HOME: '/customer/home',
    CUSTOMER_INVOICE: '/customer/invoice/:id',
    CUSTOMER_HOME2: '/customer',
    CUSTOMER_PAYMENT_SUCCESS: '/customer/payment-success',
    URL_CUSTOMER: '/customer',
    CREATE_EMPLOYEE: '/manage-accounts/create',
    IMPORT_EMPLOYEE: '/manage-accounts/import',
    CREATE_DEPARTMENT: '/manage-accounts/create-department',
    PROFILE: '/profile',
    MANAGE_INVENTORY: '/manage-inventory',
    MANAGE_PURCHASE: '/manage-purchase',
    MANAGE_PRODUCTS: '/manage-inventory/products',
    MANAGE_ACCOUNTING: '/accounting',
    IMPORT_PRODUCT: '/manage-inventory/products/import',
    SALE_IMPORT_PRODUCT: '/sale-order/products/import',
    CREATE_PRODUCT: '/manage-inventory/products/create',
    SALE_CREATE_PRODUCT: '/sale-order/products/create',
    ID_PRODUCT: '/manage-inventory/products/:id',
    INPUT_WAREHOUSE: '/manage-inventory/input-warehouse',
    VIEW_RECEIPT: '/manage-inventory/input-warehouse/:id',
    OUTPUT_WAREHOUSE: '/manage-inventory/output-warehouse',
    VIEW_DELIVERY: '/manage-inventory/output-warehouse/:id',
    CREATE_INPUT_WAREHOUSE: '/manage-inventory/input-warehouse/create',
    CREATE_OUTPUT_WAREHOUSE: '/manage-inventory/output-warehouse/create',
    SALE_ORDER: '/sale-order',
    SALE_INVOICES_DETAIL: '/sale-order/invoices/:id',
    SALE_INVOICES: '/sale-order/invoices',
    SALE_INVOICES_STATISTIC: '/sale-order/statistics',
    SALE_INVOICES_PAID: '/sale-order/invoices-paid',
    CREATE_QUOTE: '/sale-order/new-quote',
    OPEN_QUOTE: '/sale-order/:id',
    SALE_PRODUCTS: '/sale-order/products',
    VIEW_QUOTE: '/my/orders',
    VIEW_DRAFT_INVOICE: '/my/invoice',
    CUSTOMER_OPEN_INVOICE: '/my/invoice/:id',
    SALE_ORDER_CUSTOMERS: '/sale-order/customers',
    PURCHASE_PROVIDERS: '/manage-purchase/providers',
    SALE_ORDER_CUSTOMERS_CREATE: '/sale-order/customers/create',
    SALE_ORDER_CUSTOMERS_DETAIL: '/sale-order/customers/:id',
    PURCHASE_NEW: '/manage-purchase/new',

};